[package]
name = "api_in_axum"
version = "0.1.0"
edition = "2021"

[dependencies]
tower-http = { version = "0.6", features = ["fs"] }
axum = "0.8.4"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1"
tokio = { version = "1.0", features = ["full"] }
